### ISSUE TITLE
请求更新

### ISSUE THREAD

**Issue by myfreess** [veekxt/tieba_good_backup#3]

**Comment by veekxt** [comment]
已更新

**Comment by myfreess** [comment]
Traceback (most recent call last):
  File "tb_main.py", line 369, in <module>
    start_down()
  File "tb_main.py", line 366, in start_down
    down_tieba(str(tieba))                  File "tb_main.py", line 332, in down_tieba                                            down_list = make_down_list(tieba)
  File "tb_main.py", line 256, in make_down_list                                        print(i[0] + " - " + i[1])            IndexError: tuple index out of range
@veekxt 我作错什么了吗？我该怎么修复这个问题？

**Comment by veekxt** [comment]
你能提供输入吗，我无法重现这个问题。

**Comment by myfreess** [comment]
输入只有"三体"两个字 @veekxt 
python 3.7.2

**Comment by myfreess** [comment]
非常抱歉打扰，谢谢你的无私。 @veekxt
